name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Configura para rodar diariamente à meia-noite.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v2.0.0
        with:
          github_user_name: PedroHMour
          outputs: dist/snake.svg
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
